/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "upx.h"
/* Header for class com_example_admin_myapplication_model_RtProcessor */

#ifndef _Included_com_example_admin_myapplication_model_RtProcessor
#define _Included_com_example_admin_myapplication_model_RtProcessor
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_admin_myapplication_model_RtProcessor_COLOR_FORMAT_GRAY
#define com_example_admin_myapplication_model_RtProcessor_COLOR_FORMAT_GRAY 16L
#undef com_example_admin_myapplication_model_RtProcessor_COLOR_FORMAT_YUV_NV12
#define com_example_admin_myapplication_model_RtProcessor_COLOR_FORMAT_YUV_NV12 21L
#undef com_example_admin_myapplication_model_RtProcessor_COLOR_FORMAT_YUV_NV21
#define com_example_admin_myapplication_model_RtProcessor_COLOR_FORMAT_YUV_NV21 22L
#undef com_example_admin_myapplication_model_RtProcessor_COLOR_FORMAT_YUV_I420
#define com_example_admin_myapplication_model_RtProcessor_COLOR_FORMAT_YUV_I420 23L
#undef com_example_admin_myapplication_model_RtProcessor_COLOR_FORMAT_YUV_YV12
#define com_example_admin_myapplication_model_RtProcessor_COLOR_FORMAT_YUV_YV12 24L
/*
 * Class:     com_example_admin_myapplication_model_RtProcessor
 * Method:    init
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_com_example_admin_myapplication_model_RtProcessor_init
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     com_example_admin_myapplication_model_RtProcessor
 * Method:    aflocked
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_admin_myapplication_model_RtProcessor_aflocked
  (JNIEnv *, jclass);

/*
 * Class:     com_example_admin_myapplication_model_RtProcessor
 * Method:    process
 * Signature: ([BIIIIII[BIIIIII)I
 */
JNIEXPORT jint JNICALL Java_com_example_admin_myapplication_model_RtProcessor_process
  (JNIEnv *, jclass, jbyteArray, jint, jint, jint, jint, jint, jint, jbyteArray, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_example_admin_myapplication_model_RtProcessor
 * Method:    dump
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_admin_myapplication_model_RtProcessor_dump
  (JNIEnv *, jclass);

/*
 * Class:     com_example_admin_myapplication_model_RtProcessor
 * Method:    uninit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_admin_myapplication_model_RtProcessor_uninit
  (JNIEnv *, jclass);

/*
 * Class:     com_example_admin_myapplication_model_RtProcessor
 * Method:    getVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_admin_myapplication_model_RtProcessor_getVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
