/* DO NOT EDIT THIS FILE - it is machine generated */
#include <android/log.h>
#include <jni.h>
#include <include/com_example_admin_myapplication_model_RtProcessor.h>
#include <include/dcs_rt_refocus.h>

#define TAG "RT_JNI"
#define LOGD(...) __android_log_print(ANDROID_LOG_DEBUG,TAG ,__VA_ARGS__)
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO,TAG ,__VA_ARGS__)
#define LOGW(...) __android_log_print(ANDROID_LOG_WARN,TAG ,__VA_ARGS__)
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR,TAG ,__VA_ARGS__)
#define LOGF(...) __android_log_print(ANDROID_LOG_FATAL,TAG ,__VA_ARGS__)

JNIEXPORT jint JNICALL Java_com_example_admin_myapplication_model_RtProcessor_init
  (JNIEnv *, jclass, jint, jint, jint, jint){
   int result =  99;
   LOGD("init");
   return result;
  }

/*
 * Class:     com_example_admin_myapplication_model_RtProcessor
 * Method:    aflocked
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_admin_myapplication_model_RtProcessor_aflocked
  (JNIEnv *, jclass){
  int result = 123;
   dcs_rt_refocus_init(4160,3120,480,360,0);
   LOGD("aflocked");
   return result;
  }

/*
 * Class:     com_example_admin_myapplication_model_RtProcessor
 * Method:    process
 * Signature: ([BIIIIII[BIIIIII)I
 */
JNIEXPORT jint JNICALL Java_com_example_admin_myapplication_model_RtProcessor_process
  (JNIEnv *, jclass, jbyteArray, jint, jint, jint, jint, jint, jint, jbyteArray, jint, jint, jint, jint, jint, jint){

   int result = 9669;
   LOGD("process");
   return result;
  }

/*
 * Class:     com_example_admin_myapplication_model_RtProcessor
 * Method:    dump
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_admin_myapplication_model_RtProcessor_dump
  (JNIEnv *, jclass){
   int result = 99;
   LOGD("dump");
   return result;
  }

/*
 * Class:     com_example_admin_myapplication_model_RtProcessor
 * Method:    uninit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_admin_myapplication_model_RtProcessor_uninit
  (JNIEnv *, jclass){
   int result = 5555;
   LOGD("uninit");
   return result;
  }

/*
 * Class:     com_example_admin_myapplication_model_RtProcessor
 * Method:    getVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_admin_myapplication_model_RtProcessor_getVersion
  (JNIEnv *, jclass){
   int result = 6666;
   LOGD("getVersion");
   return result;

  }


