/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <include/com_example_admin_myapplication_model_RtProcessor.h>


JNIEXPORT jint JNICALL Java_com_example_admin_myapplication_model_RtProcessor_init
  (JNIEnv *, jclass, jint, jint, jint, jint){
   int result = 1;
   return result;
  }

/*
 * Class:     com_example_admin_myapplication_model_RtProcessor
 * Method:    aflocked
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_admin_myapplication_model_RtProcessor_aflocked
  (JNIEnv *, jclass){

int result = 11111;
   return result;
  }

/*
 * Class:     com_example_admin_myapplication_model_RtProcessor
 * Method:    process
 * Signature: ([BIIIIII[BIIIIII)I
 */
JNIEXPORT jint JNICALL Java_com_example_admin_myapplication_model_RtProcessor_process
  (JNIEnv *, jclass, jbyteArray, jint, jint, jint, jint, jint, jint, jbyteArray, jint, jint, jint, jint, jint, jint){

   int result = 1;
   return result;
  }

/*
 * Class:     com_example_admin_myapplication_model_RtProcessor
 * Method:    dump
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_admin_myapplication_model_RtProcessor_dump
  (JNIEnv *, jclass){
   int result = 3333;
   return result;
  }

/*
 * Class:     com_example_admin_myapplication_model_RtProcessor
 * Method:    uninit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_admin_myapplication_model_RtProcessor_uninit
  (JNIEnv *, jclass){
   int result = 5555;
   return result;
  }

/*
 * Class:     com_example_admin_myapplication_model_RtProcessor
 * Method:    getVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_admin_myapplication_model_RtProcessor_getVersion
  (JNIEnv *, jclass){
   int result = 6666;
   return result;

  }


